// Generates docs/TOOLS.md from the tool definitions, so the reference can never drift from the code.
//   npx tsx scripts/gen-tool-docs.ts
import { writeFileSync } from "node:fs";
import { z } from "zod";
import { TOOLSETS, type AnyToolSpec } from "../src/core/registry.js";
import { ALL_TOOLS } from "../src/toolsets/index.js";

const ACCESS: Record<string, string> = { read: "read", write: "**write**", destructive: "**destructive** (two-step)" };

function params(spec: AnyToolSpec): string {
  const shape = spec.input as z.ZodRawShape;
  const rows = Object.entries(shape).map(([name, schema]) => {
    const s = schema as z.ZodType;
    const json = z.toJSONSchema(s, { unrepresentable: "any" }) as { type?: string | string[]; enum?: string[]; description?: string; items?: { type?: string; enum?: string[] } };
    const optional = s.safeParse(undefined).success;
    const type = json.enum ? json.enum.map((e) => `\`${e}\``).join(" \\| ") : json.type === "array" ? `${json.items?.enum ? "enum" : (json.items?.type ?? "any")}[]` : String(json.type ?? "any");
    return `| \`${name}\`${optional ? "" : " *"} | ${type} | ${(s.description ?? json.description ?? "").replaceAll("|", "\\|").replaceAll("\n", " ")} |`;
  });
  return rows.length ? `| Parameter | Type | Description |\n|---|---|---|\n${rows.join("\n")}` : "_No parameters._";
}

const meta = 2;
const total = ALL_TOOLS.length + meta;
const core = ALL_TOOLS.filter((t) => t.core).length + meta;
const coreRead = ALL_TOOLS.filter((t) => t.core && t.access === "read").length + meta;
const by = (a: string) => ALL_TOOLS.filter((t) => t.access === a).length;

const out: string[] = [
  "# Tool reference",
  "",
  `<!-- Generated by scripts/gen-tool-docs.ts. Do not edit by hand. -->`,
  "",
  `**${total} tools** in ${Object.keys(TOOLSETS).length} toolsets: ${by("read") + meta} read, ${by("write")} write, ${by("destructive")} destructive. ` +
    `The default set (marked ★) has ${core} tools: a fresh read-only install shows its **${coreRead} read tools**, and the ${core - coreRead} default write tools appear with \`SC_MODE=write\`. Enable more with \`SC_TOOLSETS\` or the \`sc_enable_toolsets\` tool; enable writes with \`SC_MODE=write\` or \`full\`.`,
  "",
  "Parameters marked * are required.",
  "",
  "## Contents",
  "",
  ...Object.entries(TOOLSETS).map(([id, desc]) => `- [${id}](#${id}): ${desc} (${ALL_TOOLS.filter((t) => t.toolset === id).length + (id === "core" ? meta : 0)})`),
  "",
];

for (const [id, desc] of Object.entries(TOOLSETS)) {
  const tools = ALL_TOOLS.filter((t) => t.toolset === id);
  out.push(`## ${id}`, "", desc, "");
  if (id === "core") {
    out.push("### `sc_list_toolsets` ★", "", "Lists every toolset, how many tools each has and whether it is enabled. Access: read.", "");
    out.push("### `sc_enable_toolsets` ★", "", "Turns on extra toolsets for the session (sends a tools-changed notification). Access: read.", "");
  }
  out.push("| Tool | Access | What it does |", "|---|---|---|");
  for (const t of tools) out.push(`| [\`${t.name}\`](#${t.name})${t.core ? " ★" : ""} | ${ACCESS[t.access]} | ${t.title} |`);
  out.push("");
  for (const t of tools) out.push(`### \`${t.name}\`${t.core ? " ★" : ""}`, "", `${t.description}`, "", `Access: ${ACCESS[t.access]}`, "", params(t), "");
}

writeFileSync("docs/TOOLS.md", out.join("\n"));
console.log(`docs/TOOLS.md: ${total} tools, ${core} default`);
